/**
 * Niche Hunter Page — Phase E + Style-Faithful Pipeline
 * Shows: scan trigger, live scan progress, pattern grid with approve/dismiss signal UI,
 * adaptation mode badge (edit_source / style_reference / prompt_only), and Style Preferences card.
 */
import { useState, useEffect, useRef, useCallback } from "react";
import { trpc } from "@/lib/trpc";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import {
  Crosshair, CheckCircle2, XCircle, Loader2, Zap, RefreshCw,
  ExternalLink, AlertTriangle, ThumbsUp, ThumbsDown, Sparkles, ChevronDown, ChevronUp,
} from "lucide-react";
import { toast } from "sonner";

// ─── Tag definitions ──────────────────────────────────────────────────────────

const APPROVAL_TAGS = [
  { id: "great_style", label: "Great style" },
  { id: "perfect_subject", label: "Perfect subject" },
  { id: "strong_humor", label: "Strong humor" },
  { id: "niche_authentic", label: "Niche authentic" },
  { id: "clean_composition", label: "Clean composition" },
  { id: "love_colors", label: "Love the colors" },
] as const;

const REJECTION_TAGS = [
  { id: "wrong_style", label: "Wrong style" },
  { id: "bad_subject", label: "Bad subject" },
  { id: "weak_humor", label: "Weak humor" },
  { id: "off_brand", label: "Off-brand" },
  { id: "poor_composition", label: "Poor composition" },
  { id: "bad_colors", label: "Bad colors" },
  { id: "too_generic", label: "Too generic" },
  { id: "transfer_failed", label: "Transfer failed" },
] as const;

type ApprovalTag = (typeof APPROVAL_TAGS)[number]["id"];
type RejectionTag = (typeof REJECTION_TAGS)[number]["id"];

// ─── Pattern type ─────────────────────────────────────────────────────────────

type Pattern = {
  id: string;
  patternName: string;
  composition: string | null;
  colorStrategy: string | null;
  emotionalHook: string | null;
  transferablePattern: string | null;
  whyItWorks: string | null;
  adaptedConcept: string | null;
  previewImageUrl: string | null;
  productionDesignUrl: string | null;
  sourcePlatform: string | null;
  sourceTitle: string | null;
  sourceUrl: string | null;
  sourceImageUrl: string | null;
  sourceSales: number | null;
  sourceBadge: string | null;
  sourceReviewCount: number | null;
  sourceCategory: string | null;
  transferValid: boolean | null;
  transferReasoning: string | null;
  score: number | null;
  rankReasoning: string | null;
  status: "discovered" | "approved" | "dismissed";
  adaptationMode: string | null;
  approvalTags: string[] | null;
  rejectionTags: string[] | null;
  approvalReason: string | null;
  rejectionReason: string | null;
  dtfImageUrl: string | null;
  approvedAt: string | number | null;
};

// ─── Adaptation Mode Badge ────────────────────────────────────────────────────

function AdaptationModeBadge({ mode }: { mode: string | null }) {
  if (!mode) return null;

  if (mode === "edit_source" || mode === "style_reference_flagged") {
    return (
      <Badge
        variant="outline"
        className="text-[10px] px-1.5 py-0 h-5 border-amber-500/50 text-amber-400 bg-amber-500/10"
        title="Generated by editing the source Etsy image — verify style match"
      >
        <AlertTriangle className="w-2.5 h-2.5 mr-1" />
        Edit Mode — verify style
      </Badge>
    );
  }

  if (mode === "style_reference") {
    return (
      <Badge
        variant="outline"
        className="text-[10px] px-1.5 py-0 h-5 border-blue-500/50 text-blue-400 bg-blue-500/10"
        title="Generated using source image as style reference"
      >
        Style Ref
      </Badge>
    );
  }

  return (
    <Badge
      variant="outline"
      className="text-[10px] px-1.5 py-0 h-5 border-muted-foreground/30 text-muted-foreground"
      title="Generated from text prompt only (no source image)"
    >
      Prompt Only
    </Badge>
  );
}

// ─── Signal Chips (read-only, shown on approved/dismissed cards) ──────────────

function SignalChips({
  tags,
  type,
}: {
  tags: string[] | null;
  type: "approval" | "rejection";
}) {
  if (!tags || tags.length === 0) return null;

  const allTags = type === "approval" ? APPROVAL_TAGS : REJECTION_TAGS;
  const colorClass =
    type === "approval"
      ? "border-green-500/40 text-green-400 bg-green-500/10"
      : "border-red-500/40 text-red-400 bg-red-500/10";

  return (
    <div className="flex flex-wrap gap-1 mt-1">
      {tags.map((tag) => {
        const label = allTags.find((t) => t.id === tag)?.label ?? tag;
        return (
          <span
            key={tag}
            className={`text-[10px] px-1.5 py-0.5 rounded border ${colorClass}`}
          >
            {label}
          </span>
        );
      })}
    </div>
  );
}

// ─── Pattern Card ─────────────────────────────────────────────────────────────

function PatternCard({
  pattern,
  onApprove,
  onDismiss,
  onFlagEditMode,
  isActing,
}: {
  pattern: Pattern;
  onApprove: (id: string) => void;
  onDismiss: (id: string) => void;
  onFlagEditMode: (id: string) => void;
  isActing: boolean;
}) {
  return (
    <Card className="border border-border bg-card flex flex-col gap-0 min-w-0 overflow-hidden">
      <CardHeader className="pb-3 overflow-hidden">
        <div className="flex items-start justify-between gap-3 min-w-0">
          <CardTitle className="text-sm font-semibold leading-snug min-w-0 break-words">
            {pattern.patternName}
          </CardTitle>
          <Badge
            variant="outline"
            className="shrink-0 text-xs uppercase tracking-wide"
            style={{
              color:
                pattern.status === "approved"
                  ? "#22C55E"
                  : pattern.status === "dismissed"
                    ? "#EF4444"
                    : "#F59E0B",
              borderColor:
                pattern.status === "approved"
                  ? "#22C55E"
                  : pattern.status === "dismissed"
                    ? "#EF4444"
                    : "#F59E0B",
            }}
          >
            {pattern.status}
          </Badge>
        </div>

        {/* Adaptation mode badge */}
        {pattern.adaptationMode && (
          <div className="mt-1">
            <AdaptationModeBadge mode={pattern.adaptationMode} />
          </div>
        )}

        {pattern.sourceTitle && (
          <div className="mt-1">
            <p className="text-xs text-muted-foreground break-words">
              Source: {pattern.sourceTitle}
              {pattern.sourceReviewCount != null
                ? ` · ${pattern.sourceReviewCount.toLocaleString()} reviews`
                : pattern.sourceSales
                ? ` · ~${pattern.sourceSales} sales/mo`
                : ""}
            </p>
            <a
              href={
                pattern.sourceUrl
                  ? pattern.sourceUrl
                  : `https://www.etsy.com/search?q=${encodeURIComponent(
                      pattern.sourceTitle.split(" ").slice(0, 5).join(" ") + " shirt"
                    )}`
              }
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs text-muted-foreground hover:text-foreground flex items-center gap-1 mt-0.5"
            >
              <ExternalLink className="w-3 h-3" />
              {pattern.sourceUrl ? "View on Etsy" : "Search on Etsy"}
            </a>
          </div>
        )}
        {pattern.sourceCategory && (
          <div className="mt-1.5 max-w-full overflow-hidden">
            <Badge variant="outline" className="text-xs max-w-full truncate block w-fit" title={`From: ${pattern.sourceCategory}`}>
              From: {pattern.sourceCategory}
            </Badge>
          </div>
        )}
        {pattern.score != null && (
          <div className="flex items-center gap-2 mt-2">
            <div className="flex items-center gap-1.5">
              <div
                className="h-6 w-6 rounded-full flex items-center justify-center text-[10px] font-bold text-white"
                style={{
                  backgroundColor:
                    pattern.score >= 80 ? "#22C55E" : pattern.score >= 60 ? "#F59E0B" : "#EF4444",
                }}
              >
                {pattern.score}
              </div>
              <span className="text-xs text-muted-foreground font-medium">
                {pattern.score >= 80 ? "High potential" : pattern.score >= 60 ? "Moderate" : "Low fit"}
              </span>
            </div>
          </div>
        )}
        {pattern.rankReasoning && (
          <p className="text-xs italic text-muted-foreground mt-1 break-words">
            {pattern.rankReasoning}
          </p>
        )}

        {/* Approval/rejection signal chips */}
        {pattern.status === "approved" && pattern.approvalTags && pattern.approvalTags.length > 0 && (
          <div className="mt-1">
            <p className="text-[10px] text-muted-foreground uppercase tracking-wide mb-0.5">Why you approved</p>
            <SignalChips tags={pattern.approvalTags} type="approval" />
            {pattern.approvalReason && (
              <p className="text-xs text-muted-foreground mt-1 italic">"{pattern.approvalReason}"</p>
            )}
          </div>
        )}
        {pattern.status === "dismissed" && pattern.rejectionTags && pattern.rejectionTags.length > 0 && (
          <div className="mt-1">
            <p className="text-[10px] text-muted-foreground uppercase tracking-wide mb-0.5">Why you dismissed</p>
            <SignalChips tags={pattern.rejectionTags} type="rejection" />
            {pattern.rejectionReason && (
              <p className="text-xs text-muted-foreground mt-1 italic">"{pattern.rejectionReason}"</p>
            )}
          </div>
        )}
      </CardHeader>

      <CardContent className="flex flex-col gap-3 pt-0 overflow-hidden">
        {/* Real Etsy source product image */}
        {pattern.sourceImageUrl && (
          <div>
            <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-1">
              Etsy Best Seller Inspiration
            </p>
            <a
              href={pattern.sourceUrl ?? "#"}
              target="_blank"
              rel="noopener noreferrer"
              className="block rounded-md overflow-hidden border border-border bg-muted hover:opacity-90 transition-opacity"
            >
              <img
                src={pattern.sourceImageUrl}
                alt={`Etsy best seller: ${pattern.sourceTitle ?? ""}`}
                className="w-full aspect-square object-cover"
              />
            </a>
          </div>
        )}

        {/* Loading indicator when production image is still generating */}
        {pattern.sourceImageUrl && !pattern.productionDesignUrl && !pattern.previewImageUrl && pattern.adaptationMode === "edit_source" && (
          <div className="rounded-md border border-dashed border-border bg-muted/50 p-4 flex flex-col items-center justify-center gap-2 min-h-[120px]">
            <Loader2 className="w-5 h-5 animate-spin text-muted-foreground" />
            <p className="text-xs text-muted-foreground text-center">Generating niche variation...</p>
            <p className="text-[10px] text-muted-foreground/60 text-center">This takes 30–60 seconds. Page auto-refreshes.</p>
          </div>
        )}

        {/* AI-generated adapted design — productionDesignUrl (transparent) is primary */}
        {(pattern.productionDesignUrl || pattern.previewImageUrl) && (
          <div>
            {pattern.sourceImageUrl && (
              <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-1">
                {pattern.productionDesignUrl ? "Production Design (Transparent)" : "Adapted Design Preview"}
              </p>
            )}
            {/* Regenerating state: productionDesignUrl was nulled but previewImageUrl still exists */}
            {!pattern.productionDesignUrl && pattern.previewImageUrl && pattern.sourceImageUrl && (
              <div className="relative rounded-md overflow-hidden border border-border bg-muted w-full">
                <img
                  src={pattern.previewImageUrl}
                  alt={pattern.patternName}
                  className="w-full h-auto block opacity-30"
                />
                <div className="absolute inset-0 flex flex-col items-center justify-center gap-2">
                  <Loader2 className="w-5 h-5 animate-spin text-muted-foreground" />
                  <p className="text-xs text-muted-foreground font-medium">Regenerating...</p>
                  <p className="text-[10px] text-muted-foreground/60">New design in progress</p>
                </div>
              </div>
            )}
            {/* Primary: transparent production design on checkerboard */}
            {pattern.productionDesignUrl ? (
              <div
                className="rounded-md overflow-hidden border border-border w-full"
                style={{
                  backgroundImage: 'linear-gradient(45deg, #e0e0e0 25%, transparent 25%), linear-gradient(-45deg, #e0e0e0 25%, transparent 25%), linear-gradient(45deg, transparent 75%, #e0e0e0 75%), linear-gradient(-45deg, transparent 75%, #e0e0e0 75%)',
                  backgroundSize: '16px 16px',
                  backgroundPosition: '0 0, 0 8px, 8px -8px, -8px 0px',
                  backgroundColor: '#f5f5f5',
                }}
              >
                <img
                  src={pattern.productionDesignUrl}
                  alt={pattern.patternName}
                  className="w-full h-auto block"
                  style={{ display: 'block', width: '100%', height: 'auto' }}
                />
              </div>
            ) : (
              <div className="rounded-md overflow-hidden border border-border bg-muted w-full">
                <img
                  src={pattern.previewImageUrl!}
                  alt={pattern.patternName}
                  className="w-full h-auto block"
                  style={{ display: 'block', width: '100%', height: 'auto' }}
                />
              </div>
            )}
            {/* Secondary: on-tee mockup thumbnail (only if different from production) */}
            {pattern.productionDesignUrl && pattern.previewImageUrl && pattern.previewImageUrl !== pattern.productionDesignUrl && (
              <div className="mt-2">
                <p className="text-[10px] text-muted-foreground uppercase tracking-wide mb-0.5">On-Tee Preview</p>
                <div className="rounded border border-border overflow-hidden w-20 h-20">
                  <img
                    src={pattern.previewImageUrl}
                    alt="Mockup preview"
                    className="w-full h-full object-cover"
                  />
                </div>
              </div>
            )}
            <div className="hidden">legacy-fallback</div>
            {/* Flag edit-mode result button */}
            {pattern.adaptationMode === "edit_source" && pattern.status === "discovered" && (
              <Button
                size="sm"
                variant="ghost"
                className="mt-1 w-full text-xs h-7 text-amber-400 hover:text-amber-300 hover:bg-amber-500/10"
                onClick={() => onFlagEditMode(pattern.id)}
                title="The AI changed too much — flag this for a style-reference retry"
              >
                <AlertTriangle className="w-3 h-3 mr-1" />
                AI changed too much — flag for retry
              </Button>
            )}
          </div>
        )}

        {pattern.composition && (
          <div>
            <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-1">Composition</p>
            <p className="text-sm">{pattern.composition}</p>
          </div>
        )}
        {pattern.colorStrategy && (
          <div>
            <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-1">Color Strategy</p>
            <p className="text-sm">{pattern.colorStrategy}</p>
          </div>
        )}
        {pattern.emotionalHook && (
          <div>
            <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-1">Emotional Hook</p>
            <p className="text-sm">{pattern.emotionalHook}</p>
          </div>
        )}
        {pattern.whyItWorks && (
          <div>
            <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-1">Why It Works</p>
            <p className="text-sm text-muted-foreground">{pattern.whyItWorks}</p>
          </div>
        )}
        {pattern.adaptedConcept && (
          <div className="rounded-md bg-accent/10 border border-accent/30 p-3">
            <p className="text-xs font-semibold text-accent uppercase tracking-wide mb-1">Adapted Concept</p>
            <p className="text-sm font-medium">{pattern.adaptedConcept}</p>
          </div>
        )}

        {/* DTF ready indicator */}
        {pattern.status === "approved" && pattern.dtfImageUrl && (
          <div className="flex items-center gap-1.5 text-xs text-green-400">
            <CheckCircle2 className="w-3.5 h-3.5" />
            DTF-ready PNG generated
          </div>
        )}
        {pattern.status === "approved" && !pattern.dtfImageUrl && pattern.approvedAt &&
          (Date.now() - new Date(pattern.approvedAt).getTime() < 5 * 60 * 1000) && (
          <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
            <Loader2 className="w-3.5 h-3.5 animate-spin" />
            DTF extraction in progress...
          </div>
        )}

        {pattern.status === "discovered" && (
          <div className="flex gap-2 pt-1">
            <Button
              size="sm"
              className="flex-1 bg-accent text-accent-foreground hover:bg-accent/90"
              onClick={() => onApprove(pattern.id)}
              disabled={isActing}
            >
              <CheckCircle2 className="h-3.5 w-3.5 mr-1.5" />
              Approve
            </Button>
            <Button
              size="sm"
              variant="outline"
              className="flex-1"
              onClick={() => onDismiss(pattern.id)}
              disabled={isActing}
            >
              <XCircle className="h-3.5 w-3.5 mr-1.5" />
              Dismiss
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

// ─── Style Preferences Card ───────────────────────────────────────────────────

function StylePreferencesCard({ workspaceId }: { workspaceId: string }) {
  const { data: prefs } = trpc.nicheHunter.getStylePreferences.useQuery(
    { workspaceId },
    { enabled: !!workspaceId }
  );

  if (!prefs || !prefs.hasEnoughData) return null;

  return (
    <Card className="border border-border">
      <CardHeader className="pb-3">
        <CardTitle className="text-sm font-semibold flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-accent" />
          Your Style Preferences
          <span className="text-xs font-normal text-muted-foreground ml-1">
            ({prefs.totalApprovals} approved · {prefs.totalRejections} dismissed)
          </span>
        </CardTitle>
      </CardHeader>
      <CardContent className="pt-0 flex flex-col gap-3">
        {prefs.approvalSignals.length > 0 && (
          <div>
            <p className="text-xs text-muted-foreground uppercase tracking-wide mb-1.5 flex items-center gap-1">
              <ThumbsUp className="w-3 h-3 text-green-400" />
              What you love
            </p>
            <div className="flex flex-wrap gap-1.5">
              {prefs.approvalSignals.map((s) => (
                <span
                  key={s.label}
                  className="text-xs px-2 py-0.5 rounded-full border border-green-500/40 text-green-400 bg-green-500/10"
                >
                  {s.label} <span className="opacity-60">×{s.count}</span>
                </span>
              ))}
            </div>
          </div>
        )}
        {prefs.rejectionSignals.length > 0 && (
          <div>
            <p className="text-xs text-muted-foreground uppercase tracking-wide mb-1.5 flex items-center gap-1">
              <ThumbsDown className="w-3 h-3 text-red-400" />
              What you avoid
            </p>
            <div className="flex flex-wrap gap-1.5">
              {prefs.rejectionSignals.filter((s) => s.label !== "Transfer failed").map((s) => (
                <span
                  key={s.label}
                  className="text-xs px-2 py-0.5 rounded-full border border-red-500/40 text-red-400 bg-red-500/10"
                >
                  {s.label} <span className="opacity-60">×{s.count}</span>
                </span>
              ))}
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

// ─── Approve Dialog ───────────────────────────────────────────────────────────

function ApproveDialog({
  open,
  onClose,
  onConfirm,
  isPending,
}: {
  open: boolean;
  onClose: () => void;
  onConfirm: (reason: string, tags: ApprovalTag[]) => void;
  isPending: boolean;
}) {
  const [reason, setReason] = useState("");
  const [selectedTags, setSelectedTags] = useState<ApprovalTag[]>([]);

  const toggleTag = (tag: ApprovalTag) => {
    setSelectedTags((prev) =>
      prev.includes(tag) ? prev.filter((t) => t !== tag) : [...prev, tag]
    );
  };

  const handleConfirm = () => {
    onConfirm(reason, selectedTags);
    setReason("");
    setSelectedTags([]);
  };

  return (
    <Dialog open={open} onOpenChange={(v) => !v && onClose()}>
      <DialogContent className="max-w-sm" onCloseAutoFocus={(e) => e.preventDefault()}>
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <CheckCircle2 className="h-4 w-4 text-green-400" />
            Approve Pattern
          </DialogTitle>
        </DialogHeader>
        <div className="flex flex-col gap-4">
          <div>
            <p className="text-xs text-muted-foreground uppercase tracking-wide mb-2">What do you like about it?</p>
            <div className="flex flex-wrap gap-1.5">
              {APPROVAL_TAGS.map((tag) => (
                <button
                  key={tag.id}
                  onClick={() => toggleTag(tag.id)}
                  className={`text-xs px-2 py-1 rounded-full border transition-colors ${
                    selectedTags.includes(tag.id)
                      ? "border-green-500 text-green-400 bg-green-500/15"
                      : "border-border text-muted-foreground hover:border-green-500/50"
                  }`}
                >
                  {tag.label}
                </button>
              ))}
            </div>
          </div>
          <div>
            <p className="text-xs text-muted-foreground uppercase tracking-wide mb-2">Optional note</p>
            <Textarea
              placeholder="e.g. Love the vintage distressed style..."
              value={reason}
              onChange={(e) => setReason(e.target.value)}
              className="text-sm h-20 resize-none"
            />
          </div>
        </div>
        <DialogFooter className="gap-2">
          <Button variant="outline" size="sm" onClick={onClose} disabled={isPending}>
            Cancel
          </Button>
          <Button
            size="sm"
            className="bg-accent text-accent-foreground hover:bg-accent/90"
            onClick={handleConfirm}
            disabled={isPending}
          >
            {isPending ? <Loader2 className="h-3.5 w-3.5 animate-spin mr-1.5" /> : <CheckCircle2 className="h-3.5 w-3.5 mr-1.5" />}
            Approve
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// ─── Dismiss Dialog ───────────────────────────────────────────────────────────

function DismissDialog({
  open,
  onClose,
  onConfirm,
  isPending,
}: {
  open: boolean;
  onClose: () => void;
  onConfirm: (reason: string, tags: RejectionTag[]) => void;
  isPending: boolean;
}) {
  const [reason, setReason] = useState("");
  const [selectedTags, setSelectedTags] = useState<RejectionTag[]>([]);

  const toggleTag = (tag: RejectionTag) => {
    setSelectedTags((prev) =>
      prev.includes(tag) ? prev.filter((t) => t !== tag) : [...prev, tag]
    );
  };

  const handleConfirm = () => {
    onConfirm(reason, selectedTags);
    setReason("");
    setSelectedTags([]);
  };

  return (
    <Dialog open={open} onOpenChange={(v) => !v && onClose()}>
      <DialogContent className="max-w-sm" onCloseAutoFocus={(e) => e.preventDefault()}>
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <XCircle className="h-4 w-4 text-red-400" />
            Dismiss Pattern
          </DialogTitle>
        </DialogHeader>
        <div className="flex flex-col gap-4">
          <div>
            <p className="text-xs text-muted-foreground uppercase tracking-wide mb-2">Why are you dismissing it?</p>
            <div className="flex flex-wrap gap-1.5">
              {REJECTION_TAGS.map((tag) => (
                <button
                  key={tag.id}
                  onClick={() => toggleTag(tag.id)}
                  className={`text-xs px-2 py-1 rounded-full border transition-colors ${
                    selectedTags.includes(tag.id)
                      ? "border-red-500 text-red-400 bg-red-500/15"
                      : "border-border text-muted-foreground hover:border-red-500/50"
                  }`}
                >
                  {tag.label}
                </button>
              ))}
            </div>
          </div>
          <div>
            <p className="text-xs text-muted-foreground uppercase tracking-wide mb-2">Optional note</p>
            <Textarea
              placeholder="e.g. Style doesn't match our vintage aesthetic..."
              value={reason}
              onChange={(e) => setReason(e.target.value)}
              className="text-sm h-20 resize-none"
            />
          </div>
        </div>
        <DialogFooter className="gap-2">
          <Button variant="outline" size="sm" onClick={onClose} disabled={isPending}>
            Cancel
          </Button>
          <Button
            size="sm"
            variant="destructive"
            onClick={handleConfirm}
            disabled={isPending}
          >
            {isPending ? <Loader2 className="h-3.5 w-3.5 animate-spin mr-1.5" /> : <XCircle className="h-3.5 w-3.5 mr-1.5" />}
            Dismiss
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// ─── Flag Edit-Mode Dialog ───────────────────────────────────────────────────

function FlagEditModeDialog({
  open,
  onClose,
  onConfirm,
  isPending,
}: {
  open: boolean;
  onClose: () => void;
  onConfirm: (reason: string) => void;
  isPending: boolean;
}) {
  const [reason, setReason] = useState("");

  const handleConfirm = () => {
    onConfirm(reason);
    setReason("");
  };

  return (
    <Dialog open={open} onOpenChange={(v) => !v && onClose()}>
      <DialogContent className="max-w-sm" onCloseAutoFocus={(e) => e.preventDefault()}>
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <AlertTriangle className="h-4 w-4 text-amber-400" />
            Flag: AI Changed Too Much
          </DialogTitle>
        </DialogHeader>
        <div className="flex flex-col gap-4">
          <p className="text-sm text-muted-foreground">
            This pattern will be dismissed. Tell us what went wrong so future scans avoid the same mistake.
          </p>
          <div>
            <p className="text-xs text-muted-foreground uppercase tracking-wide mb-2">What did the AI get wrong?</p>
            <Textarea
              placeholder="e.g. Added elements that weren't in the source, changed the art style completely..."
              value={reason}
              onChange={(e) => setReason(e.target.value)}
              className="text-sm h-20 resize-none"
            />
          </div>
        </div>
        <DialogFooter className="gap-2">
          <Button variant="outline" size="sm" onClick={onClose} disabled={isPending}>
            Cancel
          </Button>
          <Button
            size="sm"
            className="bg-amber-600 hover:bg-amber-700 text-white"
            onClick={handleConfirm}
            disabled={isPending}
          >
            {isPending ? <Loader2 className="h-3.5 w-3.5 animate-spin mr-1.5" /> : <AlertTriangle className="h-3.5 w-3.5 mr-1.5" />}
            Flag & Dismiss
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────

export default function NicheHunter() {
  const { activeWorkspace } = useWorkspace();
  const workspaceId = activeWorkspace?.id ?? "";

  const [activeScanId, setActiveScanId] = useState<string | null>(null);
  const [actingPatternId, setActingPatternId] = useState<string | null>(null);
  const [statusFilter, setStatusFilter] = useState<"discovered" | "approved" | "dismissed" | undefined>(undefined);
  const [showSearchLog, setShowSearchLog] = useState(false);
  const [retryRemaining, setRetryRemaining] = useState(0);
  const [isRetrying, setIsRetrying] = useState(false);

  // Signal dialog state
  const [approveDialogPatternId, setApproveDialogPatternId] = useState<string | null>(null);
  const [dismissDialogPatternId, setDismissDialogPatternId] = useState<string | null>(null);
  const [flagDialogPatternId, setFlagDialogPatternId] = useState<string | null>(null);

  // Preserve grid min-height during card removals to prevent scroll jump from DOM height shrinking
  const gridRef = useRef<HTMLDivElement>(null);
  const gridMinHeight = useRef<number>(0);
  const minHeightTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Before a card is removed (optimistic update), lock the grid height
  const lockGridHeight = useCallback(() => {
    if (gridRef.current) {
      gridMinHeight.current = gridRef.current.offsetHeight;
      gridRef.current.style.minHeight = `${gridMinHeight.current}px`;
      // Release the min-height after a short delay so layout can settle
      if (minHeightTimer.current) clearTimeout(minHeightTimer.current);
      minHeightTimer.current = setTimeout(() => {
        if (gridRef.current) {
          gridRef.current.style.minHeight = '';
          gridMinHeight.current = 0;
        }
      }, 2000);
    }
  }, []);

  const utils = trpc.useUtils();

  const { data: scanStatus } = trpc.nicheHunter.getScanStatus.useQuery(
    { scanId: activeScanId ?? undefined, workspaceId },
    {
      enabled: !!workspaceId,
      refetchInterval: (query) => {
        const status = query.state.data?.status;
        return status === "running" ? 2000 : false;
      },
    }
  );

  useEffect(() => {
    if (scanStatus?.scanId && !activeScanId) {
      setActiveScanId(scanStatus.scanId);
    }
  }, [scanStatus?.scanId, activeScanId]);

  useEffect(() => {
    if (scanStatus?.status === "completed") {
      // Use refetchType 'none' so we only mark stale; the placeholderData keeps UI stable
      utils.nicheHunter.getPatterns.invalidate({ workspaceId }, { refetchType: 'none' });
      // Then do a quiet refetch that won't cause scroll jump thanks to placeholderData
      utils.nicheHunter.getPatterns.refetch({ workspaceId, status: statusFilter });
    }
  }, [scanStatus?.status, workspaceId, utils, statusFilter]);

  const { data: patterns = [], isLoading: patternsLoading } =
    trpc.nicheHunter.getPatterns.useQuery(
      { workspaceId, status: statusFilter },
      {
        enabled: !!workspaceId,
        // Keep previous data during refetch to prevent layout shifts / scroll jumps
        placeholderData: (prev) => prev,
        // Poll every 10s while any pattern has a sourceImageUrl but no productionDesignUrl
        // (fire-and-forget image gen still in progress)
        refetchInterval: (query) => {
          const data = query.state.data;
          if (!data || data.length === 0) return false;
          const hasIncomplete = data.some(
            (p: any) => p.sourceImageUrl && !p.productionDesignUrl && p.adaptationMode === "edit_source"
          );
          return hasIncomplete ? 10000 : false;
        },
      }
    );

  const retryStuck = trpc.nicheHunter.retryStuckPatterns.useMutation({
    onSuccess: (data) => {
      setRetryRemaining(data.remaining);
      if (data.remaining === 0) {
        setIsRetrying(false);
        // Mark stale without triggering immediate refetch (prevents scroll jump)
        // Data will refresh on next user interaction or window focus
        utils.nicheHunter.getPatterns.invalidate({ workspaceId }, { refetchType: 'none' });
      }
    },
    onError: () => {
      setIsRetrying(false);
    },
  });

  // Drain stuck patterns one-at-a-time via polling — Cloud Run safe (one image per request)
  useEffect(() => {
    if (!workspaceId || isRetrying) return;
    const stuckCount = patterns.filter((p: any) => p.sourceImageUrl && !p.productionDesignUrl).length;
    if (stuckCount === 0) {
      setRetryRemaining(0);
      return;
    }
    setRetryRemaining(stuckCount);
    setIsRetrying(true);
    retryStuck.mutate({ workspaceId });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [patterns, workspaceId]);

  // After each retry completes, trigger the next one after a short pause
  useEffect(() => {
    if (!isRetrying || retryRemaining === 0 || !workspaceId) return;
    const timer = setTimeout(() => {
      retryStuck.mutate({ workspaceId });
    }, 3000); // 3s gap between calls to avoid hammering the API
    return () => clearTimeout(timer);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isRetrying, retryRemaining, workspaceId]);

  const triggerScan = trpc.nicheHunter.triggerScan.useMutation({
    onSuccess: (data) => {
      if (data.alreadyRunning) {
        toast.info("A scan is already running.");
      } else {
        setActiveScanId(data.scanId);
        toast.success("Scan started! Patterns will appear below as they are discovered.");
      }
    },
    onError: (err) => toast.error(err.message),
  });

  // Scroll preservation: save scrollY before mutation, restore after invalidation settles
  const scrollYRef = useRef<number | null>(null);
  const preserveScroll = useCallback(() => {
    scrollYRef.current = window.scrollY;
  }, []);
  const restoreScroll = useCallback(() => {
    if (scrollYRef.current != null) {
      const savedY = scrollYRef.current;
      scrollYRef.current = null;
      // Use multiple rAF to ensure DOM has settled after React re-render
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          window.scrollTo(0, savedY);
        });
      });
    }
  }, []);

  const approvePattern = trpc.nicheHunter.approvePattern.useMutation({
    onMutate: async ({ patternId }) => {
      setActingPatternId(patternId);
      // Cancel outgoing refetches so they don't overwrite our update
      await utils.nicheHunter.getPatterns.cancel();
      // Snapshot current data for rollback
      const prev = utils.nicheHunter.getPatterns.getData({ workspaceId, status: statusFilter });
      // NOTE: Do NOT optimistically update here — the dialog is still open with scroll locked.
      // If we remove the card now, react-remove-scroll will restore a stale scroll position on close.
      return { prev };
    },
    onSuccess: (_data, { patternId }) => {
      // 1. Close dialog first — this releases react-remove-scroll and restores scroll correctly
      setApproveDialogPatternId(null);
      // 2. After a microtask (dialog unmount + scroll restore complete), update the cache
      setTimeout(() => {
        lockGridHeight();
        utils.nicheHunter.getPatterns.setData({ workspaceId, status: statusFilter }, (old) =>
          old?.map((p: any) => p.id === patternId ? { ...p, status: "approved" } : p) ?? []
        );
        utils.nicheHunter.getPatterns.invalidate({ workspaceId }, { refetchType: 'none' });
        utils.nicheHunter.getStylePreferences.invalidate({ workspaceId });
        utils.library.list.invalidate();
      }, 50);
      toast.success("Pattern approved! Next: Generate images in the Library, then refine in Design Studio.", {
        duration: 6000,
        action: {
          label: "Go to Library \u2192",
          onClick: () => window.location.assign(`/${activeWorkspace?.slug}/library`),
        },
      });
    },
    onError: (err, _vars, ctx) => {
      // Rollback on error
      if (ctx?.prev) {
        utils.nicheHunter.getPatterns.setData({ workspaceId, status: statusFilter }, ctx.prev);
      }
      toast.error(err.message);
    },
    onSettled: () => setActingPatternId(null),
  });

  const dismissPattern = trpc.nicheHunter.dismissPattern.useMutation({
    onMutate: async ({ patternId }) => {
      setActingPatternId(patternId);
      await utils.nicheHunter.getPatterns.cancel();
      const prev = utils.nicheHunter.getPatterns.getData({ workspaceId, status: statusFilter });
      // NOTE: Do NOT optimistically update here — dialog scroll lock is active
      return { prev };
    },
    onSuccess: (_data, { patternId }) => {
      // 1. Close dialog first — releases scroll lock and restores scroll correctly
      setDismissDialogPatternId(null);
      // 2. After dialog unmount + scroll restore, update cache
      setTimeout(() => {
        lockGridHeight();
        utils.nicheHunter.getPatterns.setData({ workspaceId, status: statusFilter }, (old) =>
          old?.map((p: any) => p.id === patternId ? { ...p, status: "dismissed" } : p) ?? []
        );
        utils.nicheHunter.getPatterns.invalidate({ workspaceId }, { refetchType: 'none' });
        utils.nicheHunter.getStylePreferences.invalidate({ workspaceId });
      }, 50);
      toast.success("Pattern dismissed.");
    },
    onError: (err, _vars, ctx) => {
      if (ctx?.prev) {
        utils.nicheHunter.getPatterns.setData({ workspaceId, status: statusFilter }, ctx.prev);
      }
      toast.error(err.message);
    },
    onSettled: () => setActingPatternId(null),
  });

  const flagEditMode = trpc.nicheHunter.flagEditModeResult.useMutation({
    onMutate: async ({ patternId }) => {
      setActingPatternId(patternId);
      await utils.nicheHunter.getPatterns.cancel();
      const prev = utils.nicheHunter.getPatterns.getData({ workspaceId, status: statusFilter });
      // NOTE: Do NOT optimistically update here — dialog scroll lock is active
      return { prev };
    },
    onSuccess: (_data, { patternId }) => {
      // 1. Close dialog first — releases scroll lock
      setFlagDialogPatternId(null);
      // 2. After dialog unmount + scroll restore, update cache
      setTimeout(() => {
        lockGridHeight();
        utils.nicheHunter.getPatterns.setData({ workspaceId, status: statusFilter }, (old) =>
          old?.map((p: any) => p.id === patternId ? { ...p, status: "dismissed", adaptationMode: "style_reference_flagged" } : p) ?? []
        );
        utils.nicheHunter.getPatterns.invalidate({ workspaceId }, { refetchType: 'none' });
      }, 50);
      toast.info("Flagged for style-reference retry. The system will use this signal in future scans.");
    },
    onError: (err, _vars, ctx) => {
      if (ctx?.prev) {
        utils.nicheHunter.getPatterns.setData({ workspaceId, status: statusFilter }, ctx.prev);
      }
      toast.error(err.message);
    },
    onSettled: () => setActingPatternId(null),
  });

  if (!activeWorkspace) {
    return (
      <div className="flex items-center justify-center h-64 text-muted-foreground">
        Loading workspace...
      </div>
    );
  }

  if (activeWorkspace.workspaceType !== "niche_hunter") {
    return (
      <div className="flex items-center justify-center h-64 text-muted-foreground">
        Niche Hunter is only available for Niche Hunter workspaces.
      </div>
    );
  }

  const isScanning = scanStatus?.status === "running";
  const discoveredCount = patterns.filter((p) => p.status === "discovered").length;
  const approvedCount = patterns.filter((p) => p.status === "approved").length;

  return (
    <div className="flex flex-col gap-6 p-6 min-w-0 overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold flex items-center gap-2">
            <Crosshair className="h-6 w-6 text-accent" />
            Niche Hunter
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            Discover transferable design patterns from hot-selling listings and adapt them for{" "}
            <span className="text-foreground font-medium">{activeWorkspace.name}</span>.
          </p>
        </div>
        <Button
          onClick={() => triggerScan.mutate({ workspaceId })}
          disabled={isScanning || triggerScan.isPending}
          className="bg-accent text-accent-foreground hover:bg-accent/90"
        >
          {isScanning || triggerScan.isPending ? (
            <>
              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              Scanning...
            </>
          ) : (
            <>
              <Zap className="h-4 w-4 mr-2" />
              Run Scan
            </>
          )}
        </Button>
      </div>

      {/* Style Preferences card — shown once enough signals exist */}
      <StylePreferencesCard workspaceId={workspaceId} />

      {/* Scan progress */}
      {scanStatus && scanStatus.status !== "none" && (
        <Card className="border border-border">
          <CardContent className="pt-4 pb-4">
            <div className="flex items-center justify-between mb-2">
              <span className="text-sm font-medium">
                {scanStatus.status === "running"
                  ? "Scan in progress..."
                  : scanStatus.status === "completed"
                    ? `Scan complete — ${scanStatus.patternsFound} patterns found`
                    : "Scan failed"}
              </span>
              <span className="text-xs text-muted-foreground">{scanStatus.progress}%</span>
            </div>
            <Progress value={scanStatus.progress} className="h-2" />
            {scanStatus.status === "failed" && scanStatus.errorLog && (
              <p className="text-xs text-destructive mt-2">{scanStatus.errorLog}</p>
            )}
          </CardContent>
        </Card>
      )}

      {/* Retry progress — uses smooth height transition to prevent scroll jump when appearing/disappearing */}
      <div
        className="grid transition-[grid-template-rows] duration-300 ease-in-out"
        style={{ gridTemplateRows: isRetrying && retryRemaining > 0 ? '1fr' : '0fr' }}
      >
        <div className="overflow-hidden">
          <Card className="border border-amber-500/30 bg-amber-500/5">
            <CardContent className="pt-3 pb-3">
              <div className="flex items-center gap-2">
                <Loader2 className="w-3.5 h-3.5 text-amber-500 animate-spin flex-shrink-0" />
                <span className="text-xs text-amber-600 dark:text-amber-400 font-medium">
                  Generating niche variations… {retryRemaining} remaining
                </span>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>

      {/* Search Log — collapsible, shown when scan has completed and has a searchLog */}
      {scanStatus && scanStatus.status !== "none" && Array.isArray((scanStatus as { searchLog?: unknown }).searchLog) && ((scanStatus as { searchLog?: unknown[] }).searchLog?.length ?? 0) > 0 && (
        <Card className="border border-border overflow-hidden">
          <CardContent className="pt-3 pb-3 overflow-hidden">
            <button
              className="flex items-center justify-between w-full text-left"
              onClick={() => setShowSearchLog(v => !v)}
            >
              <span className="text-xs font-medium text-muted-foreground uppercase tracking-wide">
                Search Log — {(scanStatus as { searchLog?: unknown[] }).searchLog?.length ?? 0} URLs pinged
              </span>
              {showSearchLog ? <ChevronUp className="w-3.5 h-3.5 text-muted-foreground" /> : <ChevronDown className="w-3.5 h-3.5 text-muted-foreground" />}
            </button>
            {showSearchLog && (
              <div className="mt-3 overflow-x-auto">
                <table className="w-full text-xs">
                  <thead>
                    <tr className="border-b border-border">
                      <th className="text-left py-1.5 pr-3 font-medium text-muted-foreground w-[180px]">Date / Time</th>
                      <th className="text-left py-1.5 pr-3 font-medium text-muted-foreground w-[90px]">Filter</th>
                      <th className="text-left py-1.5 pr-3 font-medium text-muted-foreground w-[50px]">Results</th>
                      <th className="text-left py-1.5 font-medium text-muted-foreground">Etsy URL</th>
                    </tr>
                  </thead>
                  <tbody>
                    {((scanStatus as { searchLog?: Array<{ query: string; url: string; filter: string; resultCount: number; searchedAt: string }> }).searchLog ?? []).map((entry, i) => (
                      <tr key={i} className="border-b border-border/40 last:border-0 hover:bg-muted/30 transition-colors">
                        <td className="py-1.5 pr-3 text-muted-foreground tabular-nums whitespace-nowrap">
                          {new Date(entry.searchedAt).toLocaleString()}
                        </td>
                        <td className="py-1.5 pr-3">
                          <span className={`inline-block px-1.5 py-0.5 rounded text-[10px] font-medium ${
                            entry.filter === "is_best_seller"
                              ? "bg-amber-500/15 text-amber-600 dark:text-amber-400"
                              : "bg-blue-500/15 text-blue-600 dark:text-blue-400"
                          }`}>
                            {entry.filter === "is_best_seller" ? "Best Seller" : "Popular Now"}
                          </span>
                        </td>
                        <td className="py-1.5 pr-3 tabular-nums text-muted-foreground">{entry.resultCount}</td>
                        <td className="py-1.5">
                          <a
                            href={entry.url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-primary hover:underline flex items-center gap-1 min-w-0"
                          >
                            <span className="truncate max-w-[320px]">{entry.url}</span>
                            <ExternalLink className="w-3 h-3 flex-shrink-0" />
                          </a>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {/* Stats row */}
      {patterns.length > 0 && (
        <div className="grid grid-cols-3 gap-3 overflow-hidden">
          {[
            { label: "Discovered", count: discoveredCount, color: "#F59E0B" },
            { label: "Approved", count: approvedCount, color: "#22C55E" },
            { label: "Dismissed", count: patterns.filter((p) => p.status === "dismissed").length, color: "#EF4444" },
          ].map(({ label, count, color }) => (
            <Card
              key={label}
              className="border border-border cursor-pointer hover:border-accent/50 transition-colors"
              onClick={() =>
                setStatusFilter(
                  statusFilter === label.toLowerCase() as typeof statusFilter
                    ? undefined
                    : label.toLowerCase() as typeof statusFilter
                )
              }
            >
              <CardContent className="pt-4 pb-4 text-center">
                <p className="text-2xl font-bold tabular-nums" style={{ color }}>{count}</p>
                <p className="text-xs text-muted-foreground uppercase tracking-wide mt-1">{label}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* Filter bar */}
      {patterns.length > 0 && (
        <div className="flex items-center gap-2">
          <span className="text-xs text-muted-foreground">Filter:</span>
          {(["discovered", "approved", "dismissed"] as const).map((f) => (
            <Button
              key={f}
              size="sm"
              variant={statusFilter === f ? "default" : "outline"}
              className="text-xs h-7 px-3"
              onClick={() => setStatusFilter(statusFilter === f ? undefined : f)}
            >
              {f.charAt(0).toUpperCase() + f.slice(1)}
            </Button>
          ))}
          {statusFilter && (
            <Button
              size="sm"
              variant="ghost"
              className="text-xs h-7 px-2"
              onClick={() => setStatusFilter(undefined)}
            >
              <RefreshCw className="h-3 w-3 mr-1" />
              Clear
            </Button>
          )}
        </div>
      )}

      {/* Pattern grid */}
      {patternsLoading ? (
        <div className="flex items-center justify-center h-32 text-muted-foreground">
          <Loader2 className="h-5 w-5 animate-spin mr-2" />
          Loading patterns...
        </div>
      ) : patterns.length === 0 ? (
        <div className="flex flex-col items-center justify-center h-48 text-center gap-3">
          <Crosshair className="h-10 w-10 text-muted-foreground/40" />
          <p className="text-muted-foreground text-sm">
            No patterns yet. Run a scan to discover transferable design patterns.
          </p>
        </div>
      ) : (
        <div ref={gridRef} className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4 overflow-hidden transition-[min-height] duration-300">
          {[...patterns]
            .filter((p) => statusFilter === "dismissed" ? p.status === "dismissed" : p.status !== "dismissed")
            .sort((a, b) => (b.score ?? 0) - (a.score ?? 0))
            .map((p) => (
              <PatternCard
                key={p.id}
                pattern={p as Pattern}
                onApprove={(id) => setApproveDialogPatternId(id)}
                onDismiss={(id) => setDismissDialogPatternId(id)}
                onFlagEditMode={(id) => setFlagDialogPatternId(id)}
                isActing={actingPatternId === p.id}
              />
            ))}
        </div>
      )}

      {/* Approve dialog */}
      <ApproveDialog
        open={!!approveDialogPatternId}
        onClose={() => setApproveDialogPatternId(null)}
        onConfirm={(reason, tags) => {
          if (!approveDialogPatternId) return;
          approvePattern.mutate({
            patternId: approveDialogPatternId,
            workspaceId,
            reason: reason || undefined,
            tags,
          });
        }}
        isPending={approvePattern.isPending}
      />

      {/* Dismiss dialog */}
      <DismissDialog
        open={!!dismissDialogPatternId}
        onClose={() => setDismissDialogPatternId(null)}
        onConfirm={(reason, tags) => {
          if (!dismissDialogPatternId) return;
          dismissPattern.mutate({
            patternId: dismissDialogPatternId,
            reason: reason || undefined,
            tags,
          });
        }}
        isPending={dismissPattern.isPending}
      />

      {/* Flag edit-mode dialog */}
      <FlagEditModeDialog
        open={!!flagDialogPatternId}
        onClose={() => setFlagDialogPatternId(null)}
        onConfirm={(reason) => {
          if (!flagDialogPatternId) return;
          flagEditMode.mutate({
            patternId: flagDialogPatternId,
            workspaceId,
            reason: reason || undefined,
          });
        }}
        isPending={flagEditMode.isPending}
      />
    </div>
  );
}
